#set datafile separator " "

set autoscale fix

set xdata time
set timefmt '%s'


set ytics 1 nomirror tc lt 1
set y2tics 5 nomirror tc lt 2

set yrange[0:100]
set yrange[50:100]

set y2range[10:20]


plot 'testlog' every ::1000 using 1:3 title 'Humidity' with lines, 'testlog' every ::1000 using 1:6 title 'Temperature' with lines axes x1y2 linetype 2

pause -1

set term png
set output 'plot.png'
replot
